controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    
    gamepad_publisher:
      type: gamepad/GamepadPublisher

gamepad_publisher:
  ros__parameters:
    axes:
      - "axis_0"
      - "axis_1"
      - "axis_2"
      - "axis_3"
    buttons:
      - "button_0"
      - "button_1" 
      - "button_2"
      - "button_3"