hardware:
  plugin: "remote_control::RemoteControl"
  parameters: {}

controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    joystick_publisher_controller: 
      type: remote_control::RemoteControlPublisher
      joints: []